<?php
/**
 * 原版（Genisys 0.14.x）方块/物品数据表 — 由 tools/extract_vanilla.php 自动生成，勿手改。
 * 来源：/workspace/genisys/src/pocketmine/{block,item}，对照 ID 0..*。
 */
declare(strict_types=1);

namespace Genisys\Module;

final class VanillaData
{
    public const BLOCKS = [
        0 => [
            'name' => 'Air',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Air',
        ],
        1 => [
            'name' => 'Stone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Stone',
        ],
        2 => [
            'name' => 'Grass',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Grass',
        ],
        3 => [
            'name' => 'Dirt',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Dirt',
        ],
        4 => [
            'name' => 'Cobblestone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Cobblestone',
        ],
        5 => [
            'name' => 'Oak Wood Planks',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Planks',
        ],
        6 => [
            'name' => 'Oak Sapling',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Sapling',
        ],
        7 => [
            'name' => 'Bedrock',
            'solid' => true,
            'transparent' => false,
            'hardness' => -1.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 18000000.0,
            'class' => 'Bedrock',
        ],
        8 => [
            'name' => 'Water',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Water',
        ],
        9 => [
            'name' => 'Still Water',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StillWater',
        ],
        10 => [
            'name' => 'Lava',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'Lava',
        ],
        11 => [
            'name' => 'Still Lava',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StillLava',
        ],
        12 => [
            'name' => 'Red Sand',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Sand',
        ],
        13 => [
            'name' => 'Gravel',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Gravel',
        ],
        14 => [
            'name' => 'Gold Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'GoldOre',
        ],
        15 => [
            'name' => 'Iron Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'IronOre',
        ],
        16 => [
            'name' => 'Coal Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'CoalOre',
        ],
        17 => [
            'name' => 'Oak Wood',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Wood',
        ],
        18 => [
            'name' => 'Oak Leaves',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.2,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Leaves',
        ],
        19 => [
            'name' => 'Sponge',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Sponge',
        ],
        20 => [
            'name' => 'Glass',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.3,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Glass',
        ],
        21 => [
            'name' => 'Lapis Lazuli Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'LapisOre',
        ],
        22 => [
            'name' => 'Lapis Lazuli Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Lapis',
        ],
        24 => [
            'name' => 'Sandstone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.8,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Sandstone',
        ],
        179 => [
            'name' => 'Red Sandstone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedSandstone',
        ],
        180 => [
            'name' => 'Red Sandstone Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedSandstoneStairs',
        ],
        26 => [
            'name' => 'Bed Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Bed',
        ],
        30 => [
            'name' => 'Cobweb',
            'solid' => false,
            'transparent' => true,
            'hardness' => 4.0,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Cobweb',
        ],
        31 => [
            'name' => 'Dead Shrub',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'TallGrass',
        ],
        32 => [
            'name' => 'Dead Bush',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DeadBush',
        ],
        35 => [
            'name' => 'White Wool',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.8,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Wool',
        ],
        37 => [
            'name' => 'Dandelion',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Dandelion',
        ],
        38 => [
            'name' => 'Poppy',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Flower',
        ],
        39 => [
            'name' => 'Brown Mushroom',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 1,
            'resistance' => 0.0,
            'class' => 'BrownMushroom',
        ],
        40 => [
            'name' => 'Red Mushroom',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedMushroom',
        ],
        41 => [
            'name' => 'Gold Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Gold',
        ],
        42 => [
            'name' => 'Iron Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Iron',
        ],
        43 => [
            'name' => 'Stone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DoubleSlab',
        ],
        44 => [
            'name' => 'Stone',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Slab',
        ],
        182 => [
            'name' => 'Red Sandstone Slab',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedSandstoneSlab',
        ],
        181 => [
            'name' => 'Double Red Sandstone Slab',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DoubleRedSandstoneSlab',
        ],
        45 => [
            'name' => 'Bricks',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 30.0,
            'class' => 'Bricks',
        ],
        46 => [
            'name' => 'TNT',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'TNT',
        ],
        47 => [
            'name' => 'Bookshelf',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.5,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Bookshelf',
        ],
        48 => [
            'name' => 'Moss Stone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'MossStone',
        ],
        49 => [
            'name' => 'Obsidian',
            'solid' => true,
            'transparent' => false,
            'hardness' => 35.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Obsidian',
        ],
        50 => [
            'name' => 'Torch',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'Torch',
        ],
        51 => [
            'name' => 'Fire Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'Fire',
        ],
        52 => [
            'name' => 'Monster Spawner',
            'solid' => true,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'MonsterSpawner',
        ],
        53 => [
            'name' => 'Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WoodStairs',
        ],
        54 => [
            'name' => 'Chest',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.5,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Chest',
        ],
        56 => [
            'name' => 'Diamond Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DiamondOre',
        ],
        57 => [
            'name' => 'Diamond Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Diamond',
        ],
        58 => [
            'name' => 'Crafting Table',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.5,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Workbench',
        ],
        59 => [
            'name' => 'Wheat Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Wheat',
        ],
        60 => [
            'name' => 'Farmland',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Farmland',
        ],
        61 => [
            'name' => 'Furnace',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Furnace',
        ],
        62 => [
            'name' => 'Burning Furnace',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.5,
            'tool' => 3,
            'light' => 13,
            'resistance' => 0.0,
            'class' => 'BurningFurnace',
        ],
        63 => [
            'name' => 'Sign Post',
            'solid' => false,
            'transparent' => true,
            'hardness' => 1.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SignPost',
        ],
        64 => [
            'name' => 'Wood Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WoodDoor',
        ],
        193 => [
            'name' => 'Spruce Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SpruceDoor',
        ],
        194 => [
            'name' => 'Birch Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'BirchDoor',
        ],
        195 => [
            'name' => 'Jungle Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'JungleDoor',
        ],
        196 => [
            'name' => 'Acacia Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'AcaciaDoor',
        ],
        197 => [
            'name' => 'Dark Oak Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DarkOakDoor',
        ],
        65 => [
            'name' => 'Ladder',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.4,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Ladder',
        ],
        67 => [
            'name' => 'Cobblestone Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'CobblestoneStairs',
        ],
        68 => [
            'name' => 'Wall Sign',
            'solid' => false,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WallSign',
        ],
        71 => [
            'name' => 'Iron Door Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'IronDoor',
        ],
        73 => [
            'name' => 'Redstone Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedstoneOre',
        ],
        74 => [
            'name' => 'Glowing Redstone Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 9,
            'resistance' => 0.0,
            'class' => 'GlowingRedstoneOre',
        ],
        78 => [
            'name' => 'Snow Layer',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.1,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SnowLayer',
        ],
        79 => [
            'name' => 'Ice',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Ice',
        ],
        80 => [
            'name' => 'Snow Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Snow',
        ],
        81 => [
            'name' => 'Cactus',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.4,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Cactus',
        ],
        82 => [
            'name' => 'Clay Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Clay',
        ],
        83 => [
            'name' => 'Sugarcane',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Sugarcane',
        ],
        85 => [
            'name' => 'Oak Fence',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Fence',
        ],
        86 => [
            'name' => 'Pumpkin',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Pumpkin',
        ],
        87 => [
            'name' => 'Netherrack',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.4,
            'tool' => 3,
            'light' => 0,
            'resistance' => 2.0,
            'class' => 'Netherrack',
        ],
        88 => [
            'name' => 'Soul Sand',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SoulSand',
        ],
        89 => [
            'name' => 'Glowstone',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.3,
            'tool' => 3,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'Glowstone',
        ],
        91 => [
            'name' => 'Jack o\'Lantern',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.0,
            'tool' => 4,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'LitPumpkin',
        ],
        92 => [
            'name' => 'Cake Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.5,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Cake',
        ],
        96 => [
            'name' => 'Wooden Trapdoor',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 15.0,
            'class' => 'Trapdoor',
        ],
        167 => [
            'name' => 'Iron Trapdoor',
            'solid' => true,
            'transparent' => true,
            'hardness' => 5.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 25.0,
            'class' => 'IronTrapdoor',
        ],
        98 => [
            'name' => 'Stone Bricks',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StoneBricks',
        ],
        99 => [
            'name' => 'Brown Mushroom Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 1.0,
            'class' => 'BrownMushroomBlock',
        ],
        100 => [
            'name' => 'Red Mushroom Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 1.0,
            'class' => 'RedMushroomBlock',
        ],
        101 => [
            'name' => 'Iron Bars',
            'solid' => true,
            'transparent' => true,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'IronBars',
        ],
        102 => [
            'name' => 'Glass Pane',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.3,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'GlassPane',
        ],
        103 => [
            'name' => 'Melon Block',
            'solid' => true,
            'transparent' => true,
            'hardness' => 1.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Melon',
        ],
        104 => [
            'name' => 'Pumpkin Stem',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'PumpkinStem',
        ],
        105 => [
            'name' => 'Melon Stem',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'MelonStem',
        ],
        106 => [
            'name' => 'Vines',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.2,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Vine',
        ],
        107 => [
            'name' => 'Oak Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGate',
        ],
        108 => [
            'name' => 'Brick Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 30.0,
            'class' => 'BrickStairs',
        ],
        109 => [
            'name' => 'Stone Brick Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 1.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StoneBrickStairs',
        ],
        110 => [
            'name' => 'Mycelium',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Mycelium',
        ],
        111 => [
            'name' => 'Lily Pad',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WaterLily',
        ],
        112 => [
            'name' => 'Nether Bricks',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'NetherBrick',
        ],
        90 => [
            'name' => 'Portal',
            'solid' => true,
            'transparent' => true,
            'hardness' => -1.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Portal',
        ],
        114 => [
            'name' => 'Nether Bricks Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'NetherBrickStairs',
        ],
        115 => [
            'name' => 'Nether Wart Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'NetherWart',
        ],
        116 => [
            'name' => 'Enchanting Table',
            'solid' => true,
            'transparent' => true,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 12,
            'resistance' => 6000.0,
            'class' => 'EnchantingTable',
        ],
        117 => [
            'name' => 'Brewing Stand',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.5,
            'tool' => 0,
            'light' => 1,
            'resistance' => 2.5,
            'class' => 'BrewingStand',
        ],
        120 => [
            'name' => 'End Portal Frame',
            'solid' => true,
            'transparent' => false,
            'hardness' => -1.0,
            'tool' => 0,
            'light' => 1,
            'resistance' => 18000000.0,
            'class' => 'EndPortalFrame',
        ],
        121 => [
            'name' => 'End Stone',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'EndStone',
        ],
        128 => [
            'name' => 'Sandstone Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.8,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SandstoneStairs',
        ],
        129 => [
            'name' => 'Emerald Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'EmeraldOre',
        ],
        130 => [
            'name' => 'Ender Chest',
            'solid' => true,
            'transparent' => true,
            'hardness' => 22.5,
            'tool' => 3,
            'light' => 7,
            'resistance' => 3000.0,
            'class' => 'EnderChest',
        ],
        133 => [
            'name' => 'Emerald Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Emerald',
        ],
        134 => [
            'name' => 'Spruce Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SpruceWoodStairs',
        ],
        135 => [
            'name' => 'Birch Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'BirchWoodStairs',
        ],
        136 => [
            'name' => 'Jungle Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'JungleWoodStairs',
        ],
        139 => [
            'name' => 'Mossy Cobblestone Wall',
            'solid' => false,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StoneWall',
        ],
        140 => [
            'name' => 'Flower Pot Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FlowerPot',
        ],
        141 => [
            'name' => 'Carrot Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Carrot',
        ],
        142 => [
            'name' => 'Potato Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Potato',
        ],
        145 => [
            'name' => 'Unknown #145',
            'solid' => false,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 6000.0,
            'class' => 'Anvil',
        ],
        146 => [
            'name' => 'Trapped Chest',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.5,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'TrappedChest',
        ],
        152 => [
            'name' => 'Block of Redstone',
            'solid' => true,
            'transparent' => true,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Redstone',
        ],
        155 => [
            'name' => 'Quartz Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.8,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Quartz',
        ],
        156 => [
            'name' => 'Quartz Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.8,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'QuartzStairs',
        ],
        157 => [
            'name' => 'Oak',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DoubleWoodSlab',
        ],
        158 => [
            'name' => 'Oak',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 4,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WoodSlab',
        ],
        159 => [
            'name' => 'White Stained Clay',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.25,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StainedClay',
        ],
        161 => [
            'name' => 'Acacia Leaves',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Leaves2',
        ],
        162 => [
            'name' => 'Acacia Wood',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Wood2',
        ],
        163 => [
            'name' => 'Acacia Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'AcaciaWoodStairs',
        ],
        164 => [
            'name' => 'Dark Oak Wood Stairs',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DarkOakWoodStairs',
        ],
        165 => [
            'name' => 'Slime Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'SlimeBlock',
        ],
        168 => [
            'name' => 'Prismarine',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Prismarine',
        ],
        169 => [
            'name' => 'Sea Lantern',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.3,
            'tool' => 0,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'SeaLantern',
        ],
        170 => [
            'name' => 'Hay Bale',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'HayBale',
        ],
        171 => [
            'name' => 'White Carpet',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.1,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Carpet',
        ],
        172 => [
            'name' => 'Hardened Clay',
            'solid' => true,
            'transparent' => false,
            'hardness' => 1.25,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'HardenedClay',
        ],
        173 => [
            'name' => 'Coal Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 5.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Coal',
        ],
        174 => [
            'name' => 'Packed Ice',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'PackedIce',
        ],
        175 => [
            'name' => 'Sunflower',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DoublePlant',
        ],
        183 => [
            'name' => 'Spruce Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGateSpruce',
        ],
        184 => [
            'name' => 'Birch Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGateBirch',
        ],
        185 => [
            'name' => 'Jungle Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGateJungle',
        ],
        186 => [
            'name' => 'Dark Oak Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGateDarkOak',
        ],
        187 => [
            'name' => 'Acacia Fence Gate',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'FenceGateAcacia',
        ],
        199 => [
            'name' => 'Item Frame',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'ItemFrame',
        ],
        198 => [
            'name' => 'Grass Path',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.6,
            'tool' => 2,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'GrassPath',
        ],
        243 => [
            'name' => 'Podzol',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.5,
            'tool' => 2,
            'light' => 0,
            'resistance' => 2.5,
            'class' => 'Podzol',
        ],
        244 => [
            'name' => 'Beetroot Block',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Beetroot',
        ],
        245 => [
            'name' => 'Stonecutter',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Stonecutter',
        ],
        246 => [
            'name' => 'Glowing Obsidian',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 12,
            'resistance' => 0.0,
            'class' => 'GlowingObsidian',
        ],
        247 => [
            'name' => 'Nether Reactor',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'NetherReactor',
        ],
        113 => [
            'name' => 'Nether Brick Fence',
            'solid' => true,
            'transparent' => true,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'NetherBrickFence',
        ],
        27 => [
            'name' => 'PoweredRail',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.7,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'PoweredRail',
        ],
        66 => [
            'name' => 'Rail',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.7,
            'tool' => 0,
            'light' => 0,
            'resistance' => 3.5,
            'class' => 'Rail',
        ],
        72 => [
            'name' => 'Wooden Pressure Plate',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WoodenPressurePlate',
        ],
        70 => [
            'name' => 'Stone Pressure Plate',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StonePressurePlate',
        ],
        147 => [
            'name' => 'Light Weighted Pressure Plate',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'LightWeightedPressurePlate',
        ],
        148 => [
            'name' => 'Heavy Weighted Pressure Plate',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'HeavyWeightedPressurePlate',
        ],
        55 => [
            'name' => 'Redstone Wire',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'RedstoneWire',
        ],
        124 => [
            'name' => 'Active Redstone Lamp',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.3,
            'tool' => 3,
            'light' => 15,
            'resistance' => 0.0,
            'class' => 'ActiveRedstoneLamp',
        ],
        123 => [
            'name' => 'Inactive Redstone Lamp',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'InactiveRedstoneLamp',
        ],
        76 => [
            'name' => 'Redstone Torch',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 7,
            'resistance' => 0.0,
            'class' => 'RedstoneTorch',
        ],
        75 => [
            'name' => 'Unknown #75',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'UnlitRedstoneTorch',
        ],
        143 => [
            'name' => 'Wooden Button',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.5,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'WoodenButton',
        ],
        77 => [
            'name' => 'Stone Button',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'StoneButton',
        ],
        69 => [
            'name' => 'Lever',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.5,
            'tool' => 0,
            'light' => 0,
            'resistance' => 2.5,
            'class' => 'Lever',
        ],
        151 => [
            'name' => 'Daylight Sensor',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 1.0,
            'class' => 'DaylightDetector',
        ],
        178 => [
            'name' => 'Unknown #178',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DaylightDetectorInverted',
        ],
        25 => [
            'name' => 'Noteblock',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.8,
            'tool' => 4,
            'light' => 0,
            'resistance' => 4.0,
            'class' => 'Noteblock',
        ],
        144 => [
            'name' => 'Mob Head',
            'solid' => false,
            'transparent' => true,
            'hardness' => 1.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'MobHead',
        ],
        153 => [
            'name' => 'Nether Quartz Ore',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 15.0,
            'class' => 'NetherQuartzOre',
        ],
        126 => [
            'name' => 'Activator Rail',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'ActivatorRail',
        ],
        127 => [
            'name' => 'Cocoa Block',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.2,
            'tool' => 0,
            'light' => 0,
            'resistance' => 15.0,
            'class' => 'CocoaBlock',
        ],
        28 => [
            'name' => 'Detector Rail',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'DetectorRail',
        ],
        132 => [
            'name' => 'Tripwire',
            'solid' => true,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 5,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Tripwire',
        ],
        131 => [
            'name' => 'Tripwire Hook',
            'solid' => true,
            'transparent' => false,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'TripwireHook',
        ],
        23 => [
            'name' => 'Dispenser',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Dispenser',
        ],
        125 => [
            'name' => 'Dropper',
            'solid' => true,
            'transparent' => false,
            'hardness' => 3.5,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Dropper',
        ],
        94 => [
            'name' => 'Powered Repeater',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'PoweredRepeater',
        ],
        93 => [
            'name' => 'Unpowered Repeater',
            'solid' => false,
            'transparent' => true,
            'hardness' => 0.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'UnpoweredRepeater',
        ],
        118 => [
            'name' => 'Cauldron',
            'solid' => true,
            'transparent' => false,
            'hardness' => 2.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Cauldron',
        ],
        95 => [
            'name' => 'Invisible Bedrock',
            'solid' => true,
            'transparent' => true,
            'hardness' => -1.0,
            'tool' => 0,
            'light' => 0,
            'resistance' => 18000000.0,
            'class' => 'InvisibleBedrock',
        ],
        154 => [
            'name' => 'Hopper',
            'solid' => true,
            'transparent' => true,
            'hardness' => 3.0,
            'tool' => 3,
            'light' => 0,
            'resistance' => 0.0,
            'class' => 'Hopper',
        ],
    ];

    public const BLOCK_META_NAMES = [
        1 => [
            'mask' => 7,
            'names' => [
                'Stone',
                'Granite',
                'Polished Granite',
                'Diorite',
                'Polished Diorite',
                'Andesite',
                'Polished Andesite',
                'Unknown Stone',
            ],
        ],
        5 => [
            'mask' => 7,
            'names' => [
                'Oak Wood Planks',
                'Spruce Wood Planks',
                'Birch Wood Planks',
                'Jungle Wood Planks',
                'Acacia Wood Planks',
                'Dark Oak Wood Planks',
                'Unknown Planks',
                'Unknown Planks',
            ],
        ],
        6 => [
            'mask' => 7,
            'names' => [
                'Oak Sapling',
                'Spruce Sapling',
                'Birch Sapling',
                'Jungle Sapling',
                'Acacia Sapling',
                'Dark Oak Sapling',
                '',
                '',
            ],
        ],
        17 => [
            'mask' => 3,
            'names' => [
                'Oak Wood',
                'Spruce Wood',
                'Birch Wood',
                'Jungle Wood',
            ],
        ],
        18 => [
            'mask' => 3,
            'names' => [
                'Oak Leaves',
                'Spruce Leaves',
                'Birch Leaves',
                'Jungle Leaves',
            ],
        ],
        24 => [
            'mask' => 3,
            'names' => [
                'Sandstone',
                'Chiseled Sandstone',
                'Smooth Sandstone',
                '',
            ],
        ],
        179 => [
            'mask' => 3,
            'names' => [
                'Red Sandstone',
                'Chiseled Red Sandstone',
                'Smooth Red Sandstone',
                '',
            ],
        ],
        31 => [
            'mask' => 3,
            'names' => [
                'Dead Shrub',
                'Tall Grass',
                'Fern',
                '',
            ],
        ],
        35 => [
            'mask' => 15,
            'names' => [
                'White Wool',
                'Orange Wool',
                'Magenta Wool',
                'Light Blue Wool',
                'Yellow Wool',
                'Lime Wool',
                'Pink Wool',
                'Gray Wool',
                'Light Gray Wool',
                'Cyan Wool',
                'Purple Wool',
                'Blue Wool',
                'Brown Wool',
                'Green Wool',
                'Red Wool',
                'Black Wool',
            ],
        ],
        38 => [
            'mask' => 15,
            'names' => [
                'Poppy',
                'Blue Orchid',
                'Allium',
                'Azure Bluet',
                'Red Tulip',
                'Orange Tulip',
                'White Tulip',
                'Pink Tulip',
                'Oxeye Daisy',
                'Unknown',
                'Unknown',
                'Unknown',
                'Unknown',
                'Unknown',
                'Unknown',
                'Unknown',
            ],
        ],
        43 => [
            'mask' => 7,
            'names' => [
                'Stone',
                'Sandstone',
                'Wooden',
                'Cobblestone',
                'Brick',
                'Stone Brick',
                'Quartz',
                'Nether Brick',
            ],
        ],
        44 => [
            'mask' => 8,
            'names' => [
                'Stone',
                'Sandstone',
                'Wooden',
                'Cobblestone',
                'Brick',
                'Stone Brick',
                'Quartz',
                '',
            ],
        ],
        85 => [
            'mask' => 7,
            'names' => [
                'Oak Fence',
                'Spruce Fence',
                'Birch Fence',
                'Jungle Fence',
                'Acacia Fence',
                'Dark Oak Fence',
            ],
        ],
        98 => [
            'mask' => 3,
            'names' => [
                'Stone Bricks',
                'Mossy Stone Bricks',
                'Cracked Stone Bricks',
                'Chiseled Stone Bricks',
            ],
        ],
        155 => [
            'mask' => 3,
            'names' => [
                'Quartz Block',
                'Chiseled Quartz Block',
                'Quartz Pillar',
                'Quartz Block',
            ],
        ],
        157 => [
            'mask' => 7,
            'names' => [
                'Oak',
                'Spruce',
                'Birch',
                'Jungle',
                'Acacia',
                'Dark Oak',
                '',
                '',
            ],
        ],
        158 => [
            'mask' => 8,
            'names' => [
                'Oak',
                'Spruce',
                'Birch',
                'Jungle',
                'Acacia',
                'Dark Oak',
                '',
                '',
            ],
        ],
        159 => [
            'mask' => 15,
            'names' => [
                'White Stained Clay',
                'Orange Stained Clay',
                'Magenta Stained Clay',
                'Light Blue Stained Clay',
                'Yellow Stained Clay',
                'Lime Stained Clay',
                'Pink Stained Clay',
                'Gray Stained Clay',
                'Light Gray Stained Clay',
                'Cyan Stained Clay',
                'Purple Stained Clay',
                'Blue Stained Clay',
                'Brown Stained Clay',
                'Green Stained Clay',
                'Red Stained Clay',
                'Black Stained Clay',
            ],
        ],
        161 => [
            'mask' => 1,
            'names' => [
                'Acacia Leaves',
                'Dark Oak Leaves',
            ],
        ],
        162 => [
            'mask' => 3,
            'names' => [
                'Acacia Wood',
                'Dark Oak Wood',
                'Unknown',
                'Unknown',
            ],
        ],
        168 => [
            'mask' => 3,
            'names' => [
                'Prismarine',
                'Dark Prismarine',
                'Prismarine Bricks',
            ],
        ],
        171 => [
            'mask' => 15,
            'names' => [
                'White Carpet',
                'Orange Carpet',
                'Magenta Carpet',
                'Light Blue Carpet',
                'Yellow Carpet',
                'Lime Carpet',
                'Pink Carpet',
                'Gray Carpet',
                'Light Gray Carpet',
                'Cyan Carpet',
                'Purple Carpet',
                'Blue Carpet',
                'Brown Carpet',
                'Green Carpet',
                'Red Carpet',
                'Black Carpet',
            ],
        ],
        175 => [
            'mask' => 7,
            'names' => [
                'Sunflower',
                'Lilac',
                'Double Tallgrass',
                'Large Fern',
                'Rose Bush',
                'Peony',
            ],
        ],
    ];

    public const ITEMS = [
        338 => [
            'name' => 'Sugar Cane',
            'class' => 'Sugarcane',
        ],
        295 => [
            'name' => 'Wheat Seeds',
            'class' => 'WheatSeeds',
        ],
        361 => [
            'name' => 'Pumpkin Seeds',
            'class' => 'PumpkinSeeds',
        ],
        362 => [
            'name' => 'Melon Seeds',
            'class' => 'MelonSeeds',
        ],
        282 => [
            'name' => 'Mushroom Stew',
            'class' => 'MushroomStew',
        ],
        413 => [
            'name' => 'Rabbit Stew',
            'class' => 'RabbitStew',
        ],
        459 => [
            'name' => 'Beetroot Soup',
            'class' => 'BeetrootSoup',
        ],
        391 => [
            'name' => 'Carrot',
            'class' => 'Carrot',
        ],
        392 => [
            'name' => 'Potato',
            'class' => 'Potato',
        ],
        458 => [
            'name' => 'Beetroot Seeds',
            'class' => 'BeetrootSeeds',
        ],
        323 => [
            'name' => 'Sign',
            'class' => 'Sign',
        ],
        324 => [
            'name' => 'Wooden Door',
            'class' => 'WoodenDoor',
        ],
        427 => [
            'name' => 'Spruce Door',
            'class' => 'SpruceDoor',
        ],
        428 => [
            'name' => 'Birch Door',
            'class' => 'BirchDoor',
        ],
        429 => [
            'name' => 'Jungle Door',
            'class' => 'JungleDoor',
        ],
        430 => [
            'name' => 'Acacia Door',
            'class' => 'AcaciaDoor',
        ],
        431 => [
            'name' => 'Dark Oak Door',
            'class' => 'DarkOakDoor',
        ],
        325 => [
            'name' => 'Bucket',
            'class' => 'Bucket',
        ],
        330 => [
            'name' => 'Iron Door',
            'class' => 'IronDoor',
        ],
        354 => [
            'name' => 'Cake',
            'class' => 'Cake',
        ],
        355 => [
            'name' => 'Bed',
            'class' => 'Bed',
        ],
        321 => [
            'name' => 'Painting',
            'class' => 'Painting',
        ],
        263 => [
            'name' => 'Coal',
            'class' => 'Coal',
        ],
        260 => [
            'name' => 'Apple',
            'class' => 'Apple',
        ],
        383 => [
            'name' => 'Spawn Egg',
            'class' => 'SpawnEgg',
        ],
        264 => [
            'name' => 'Diamond',
            'class' => 'Diamond',
        ],
        280 => [
            'name' => 'Stick',
            'class' => 'Stick',
        ],
        332 => [
            'name' => 'Snowball',
            'class' => 'Snowball',
        ],
        281 => [
            'name' => 'Bowl',
            'class' => 'Bowl',
        ],
        288 => [
            'name' => 'Feather',
            'class' => 'Feather',
        ],
        336 => [
            'name' => 'Brick',
            'class' => 'Brick',
        ],
        298 => [
            'name' => 'Leather Cap',
            'class' => 'LeatherCap',
        ],
        299 => [
            'name' => 'Leather Tunic',
            'class' => 'LeatherTunic',
        ],
        300 => [
            'name' => 'Leather Pants',
            'class' => 'LeatherPants',
        ],
        301 => [
            'name' => 'Leather Boots',
            'class' => 'LeatherBoots',
        ],
        302 => [
            'name' => 'Chainmail Helmet',
            'class' => 'ChainHelmet',
        ],
        303 => [
            'name' => 'Chain Chestplate',
            'class' => 'ChainChestplate',
        ],
        304 => [
            'name' => 'Chain Leggings',
            'class' => 'ChainLeggings',
        ],
        305 => [
            'name' => 'Chainmail Boots',
            'class' => 'ChainBoots',
        ],
        306 => [
            'name' => 'Iron Helmet',
            'class' => 'IronHelmet',
        ],
        307 => [
            'name' => 'Iron Chestplate',
            'class' => 'IronChestplate',
        ],
        308 => [
            'name' => 'Iron Leggings',
            'class' => 'IronLeggings',
        ],
        309 => [
            'name' => 'Iron Boots',
            'class' => 'IronBoots',
        ],
        314 => [
            'name' => 'Gold Helmet',
            'class' => 'GoldHelmet',
        ],
        315 => [
            'name' => 'Gold Chestplate',
            'class' => 'GoldChestplate',
        ],
        316 => [
            'name' => 'Gold Leggings',
            'class' => 'GoldLeggings',
        ],
        317 => [
            'name' => 'Gold Boots',
            'class' => 'GoldBoots',
        ],
        310 => [
            'name' => 'Diamond Helmet',
            'class' => 'DiamondHelmet',
        ],
        311 => [
            'name' => 'Diamond Chestplate',
            'class' => 'DiamondChestplate',
        ],
        312 => [
            'name' => 'Diamond Leggings',
            'class' => 'DiamondLeggings',
        ],
        313 => [
            'name' => 'Diamond Boots',
            'class' => 'DiamondBoots',
        ],
        267 => [
            'name' => 'Iron Sword',
            'class' => 'IronSword',
        ],
        265 => [
            'name' => 'Iron Ingot',
            'class' => 'IronIngot',
        ],
        266 => [
            'name' => 'Gold Ingot',
            'class' => 'GoldIngot',
        ],
        256 => [
            'name' => 'Iron Shovel',
            'class' => 'IronShovel',
        ],
        257 => [
            'name' => 'Iron Pickaxe',
            'class' => 'IronPickaxe',
        ],
        258 => [
            'name' => 'Iron Axe',
            'class' => 'IronAxe',
        ],
        292 => [
            'name' => 'Iron Hoe',
            'class' => 'IronHoe',
        ],
        276 => [
            'name' => 'Diamond Sword',
            'class' => 'DiamondSword',
        ],
        277 => [
            'name' => 'Diamond Shovel',
            'class' => 'DiamondShovel',
        ],
        278 => [
            'name' => 'Diamond Pickaxe',
            'class' => 'DiamondPickaxe',
        ],
        279 => [
            'name' => 'Diamond Axe',
            'class' => 'DiamondAxe',
        ],
        293 => [
            'name' => 'Diamond Hoe',
            'class' => 'DiamondHoe',
        ],
        283 => [
            'name' => 'Gold Sword',
            'class' => 'GoldSword',
        ],
        284 => [
            'name' => 'Gold Shovel',
            'class' => 'GoldShovel',
        ],
        285 => [
            'name' => 'Gold Pickaxe',
            'class' => 'GoldPickaxe',
        ],
        286 => [
            'name' => 'Gold Axe',
            'class' => 'GoldAxe',
        ],
        294 => [
            'name' => 'Gold Hoe',
            'class' => 'GoldHoe',
        ],
        272 => [
            'name' => 'Stone Sword',
            'class' => 'StoneSword',
        ],
        273 => [
            'name' => 'Stone Shovel',
            'class' => 'StoneShovel',
        ],
        274 => [
            'name' => 'Stone Pickaxe',
            'class' => 'StonePickaxe',
        ],
        275 => [
            'name' => 'Stone Axe',
            'class' => 'StoneAxe',
        ],
        291 => [
            'name' => 'Stone Hoe',
            'class' => 'StoneHoe',
        ],
        268 => [
            'name' => 'Wooden Sword',
            'class' => 'WoodenSword',
        ],
        269 => [
            'name' => 'Wooden Shovel',
            'class' => 'WoodenShovel',
        ],
        270 => [
            'name' => 'Wooden Pickaxe',
            'class' => 'WoodenPickaxe',
        ],
        271 => [
            'name' => 'Wooden Axe',
            'class' => 'WoodenAxe',
        ],
        290 => [
            'name' => 'Wooden Hoe',
            'class' => 'WoodenHoe',
        ],
        259 => [
            'name' => 'Flint and Steel',
            'class' => 'FlintSteel',
        ],
        359 => [
            'name' => 'Shears',
            'class' => 'Shears',
        ],
        261 => [
            'name' => 'Bow',
            'class' => 'Bow',
        ],
        349 => [
            'name' => 'Raw Fish',
            'class' => 'Fish',
        ],
        350 => [
            'name' => 'Cooked Fish',
            'class' => 'CookedFish',
        ],
        406 => [
            'name' => 'Quartz',
            'class' => 'Quartz',
        ],
        373 => [
            'name' => 'Potion',
            'class' => 'Potion',
        ],
        374 => [
            'name' => 'Glass Bottle',
            'class' => 'GlassBottle',
        ],
        438 => [
            'name' => 'Splash Potion',
            'class' => 'SplashPotion',
        ],
        384 => [
            'name' => 'Bottle o\' Enchanting',
            'class' => 'EnchantingBottle',
        ],
        333 => [
            'name' => 'Boat',
            'class' => 'Boat',
        ],
        328 => [
            'name' => 'Minecart',
            'class' => 'Minecart',
        ],
        262 => [
            'name' => 'Arrow',
            'class' => 'Arrow',
        ],
        287 => [
            'name' => 'String',
            'class' => 'ItemString',
        ],
        289 => [
            'name' => 'Gunpowder',
            'class' => 'Gunpowder',
        ],
        296 => [
            'name' => 'Wheat',
            'class' => 'Wheat',
        ],
        297 => [
            'name' => 'Bread',
            'class' => 'Bread',
        ],
        318 => [
            'name' => 'Flint',
            'class' => 'Flint',
        ],
        319 => [
            'name' => 'Raw Porkchop',
            'class' => 'RawPorkchop',
        ],
        320 => [
            'name' => 'Cooked Porkchop',
            'class' => 'CookedPorkchop',
        ],
        322 => [
            'name' => 'Golden Apple',
            'class' => 'GoldenApple',
        ],
        331 => [
            'name' => 'Redstone',
            'class' => 'Redstone',
        ],
        334 => [
            'name' => 'Leather',
            'class' => 'Leather',
        ],
        337 => [
            'name' => 'Clay',
            'class' => 'Clay',
        ],
        339 => [
            'name' => 'Paper',
            'class' => 'Paper',
        ],
        340 => [
            'name' => 'Book',
            'class' => 'Book',
        ],
        341 => [
            'name' => 'Slimeball',
            'class' => 'Slimeball',
        ],
        344 => [
            'name' => 'Egg',
            'class' => 'Egg',
        ],
        345 => [
            'name' => 'Compass',
            'class' => 'Compass',
        ],
        347 => [
            'name' => 'Clock',
            'class' => 'Clock',
        ],
        348 => [
            'name' => 'Glowstone Dust',
            'class' => 'GlowstoneDust',
        ],
        351 => [
            'name' => 'Cocoa Beans',
            'class' => 'Dye',
        ],
        352 => [
            'name' => 'Bone',
            'class' => 'Bone',
        ],
        353 => [
            'name' => 'Sugar',
            'class' => 'Sugar',
        ],
        357 => [
            'name' => 'Cookie',
            'class' => 'Cookie',
        ],
        360 => [
            'name' => 'Melon',
            'class' => 'Melon',
        ],
        363 => [
            'name' => 'Raw Beef',
            'class' => 'RawBeef',
        ],
        364 => [
            'name' => 'Steak',
            'class' => 'Steak',
        ],
        365 => [
            'name' => 'Raw Chicken',
            'class' => 'RawChicken',
        ],
        366 => [
            'name' => 'Cooked Chicken',
            'class' => 'CookedChicken',
        ],
        371 => [
            'name' => 'Gold Nugget',
            'class' => 'GoldNugget',
        ],
        388 => [
            'name' => 'Emerald',
            'class' => 'Emerald',
        ],
        389 => [
            'name' => 'Item Frame',
            'class' => 'ItemFrame',
        ],
        390 => [
            'name' => 'Flower Pot',
            'class' => 'FlowerPot',
        ],
        393 => [
            'name' => 'Baked Potato',
            'class' => 'BakedPotato',
        ],
        400 => [
            'name' => 'Pumpkin Pie',
            'class' => 'PumpkinPie',
        ],
        405 => [
            'name' => 'Nether Brick',
            'class' => 'NetherBrick',
        ],
        379 => [
            'name' => 'Brewing Stand',
            'class' => 'BrewingStand',
        ],
        457 => [
            'name' => 'Beetroot',
            'class' => 'Beetroot',
        ],
        397 => [
            'name' => 'Skull',
            'class' => 'Skull',
        ],
        411 => [
            'name' => 'Raw Rabbit',
            'class' => 'RawRabbit',
        ],
        412 => [
            'name' => 'Cooked Rabbit',
            'class' => 'CookedRabbit',
        ],
        396 => [
            'name' => 'Golden Carrot',
            'class' => 'GoldenCarrot',
        ],
        372 => [
            'name' => 'Nether Wart',
            'class' => 'NetherWart',
        ],
        375 => [
            'name' => 'Spider Eye',
            'class' => 'SpiderEye',
        ],
        376 => [
            'name' => 'Fermented Spider Eye',
            'class' => 'FermentedSpiderEye',
        ],
        377 => [
            'name' => 'Blaze Powder',
            'class' => 'BlazePowder',
        ],
        378 => [
            'name' => 'Magma Cream',
            'class' => 'MagmaCream',
        ],
        382 => [
            'name' => 'Glistering Melon',
            'class' => 'GlisteringMelon',
        ],
        403 => [
            'name' => 'Enchanted Book',
            'class' => 'EnchantedBook',
        ],
        356 => [
            'name' => 'Repeater',
            'class' => 'Repeater',
        ],
        380 => [
            'name' => 'Cauldron',
            'class' => 'Cauldron',
        ],
        367 => [
            'name' => 'Rotten Flesh',
            'class' => 'RottenFlesh',
        ],
        368 => [
            'name' => 'Ender Pearl',
            'class' => 'EnderPearl',
        ],
        466 => [
            'name' => 'Enchanted Golden Apple',
            'class' => 'EnchantedGoldenApple',
        ],
        423 => [
            'name' => 'Raw Mutton',
            'class' => 'RawMutton',
        ],
        424 => [
            'name' => 'Cooked Mutton',
            'class' => 'CookedMutton',
        ],
        410 => [
            'name' => 'Hopper',
            'class' => 'Hopper',
        ],
        422 => [
            'name' => 'Prismarine Crystals',
            'class' => 'PrismarineCrystals',
        ],
        409 => [
            'name' => 'Prismarine Shard',
            'class' => 'PrismarineShard',
        ],
        399 => [
            'name' => 'Nether Star',
            'class' => 'NetherStar',
        ],
    ];

    public const ITEM_META_NAMES = [
        263 => [
            1 => 'Charcoal',
        ],
        349 => [
            1 => 'Raw Salmon',
            2 => 'Clownfish',
            3 => 'Pufferfish',
        ],
        350 => [
            1 => 'Cooked Salmon',
        ],
        373 => [
            0 => 'Water Bottle',
            1 => 'Mundane Potion',
            2 => 'Mundane Potion',
            3 => 'Thick Potion',
            4 => 'Awkward Potion',
            7 => 'Potion of Invisibility',
            8 => 'Potion of Invisibility',
            9 => 'Potion of Leaping',
            10 => 'Potion of Leaping',
            11 => 'Potion of Leaping II',
            12 => 'Potion of Fire Resistance',
            13 => 'Potion of Fire Resistance',
            14 => 'Potion of Swiftness',
            15 => 'Potion of Swiftness',
            16 => 'Potion of Swiftness II',
            17 => 'Potion of Slowness',
            18 => 'Potion of Slowness',
            19 => 'Potion of Water Breathing',
            20 => 'Potion of Water Breathing',
            23 => 'Potion of Harming',
            24 => 'Potion of Harming II',
            25 => 'Potion of Poison',
            26 => 'Potion of Poison',
            27 => 'Potion of Poison II',
            21 => 'Potion of Healing',
            22 => 'Potion of Healing II',
            5 => 'Potion of Night Vision',
            6 => 'Potion of Night Vision',
            31 => 'Potion of Strength',
            32 => 'Potion of Strength',
            33 => 'Potion of Strength II',
            28 => 'Potion of Regeneration',
            29 => 'Potion of Regeneration',
            30 => 'Potion of Regeneration II',
            34 => 'Potion of Weakness',
            35 => 'Potion of Weakness',
        ],
        351 => [
            'Ink Sac',
            'Rose Red',
            'Cactus Green',
            'Cocoa Beans',
            'Lapis Lazuli',
            'Purple Dye',
            'Cyan Dye',
            'Light Gray Dye',
            'Gray Dye',
            'Pink Dye',
            'Lime Dye',
            'Dandelion Yellow',
            'Light Blue Dye',
            'Magenta Dye',
            'Orange Dye',
            'Bone Meal',
        ],
    ];
}
